### PR TITLE
Feature f32

### PR DESCRIPTION
**Pull request by hakolao**
Hi, thanks for this library.

I needed `f32` version, so I thought I'd PR it also.

Let me know if this won't do :D

### CODE REVIEW

**Comment by hakolao** [comment]
I am using the `contour_lines` function only, and with the following use case: Turning 2d bitmaps into contour lines.

image

**Comment by mthh** [comment]
Hi and thank you for your contribution (as well as for showing your example use case!).

I'll take a closer look and let you know if needed, or merge it and make a new release otherwise.

**Comment by hakolao** [comment]
I didn't use any crate, just:

```
#[cfg(feature = "f32")]
pub type Float = f32;
#[cfg(not(feature = "f32"))]
pub type Float = f64;
```

**Comment by hakolao** [comment]
Perhaps the more generic T route would be more idiomatic, I kinda went as simple as possible :), feature-gated it and made it so it doesn't break anything.

**Comment by mthh** [comment]
> I didn't use any crate

Indeed, sorry for the confusion !

Using `num-traits` requires quite some work (whereas your proposal is simpler and covers the use case of using f32 or f64).

I'll merge your PR and make a new release. Maybe in a future release I'll integrate num-traits.

**Comment by hakolao** [comment]
great! Thanks :)

**Comment by mthh** [comment]
Published on crates.io.

**Pull request merged**
