### PR TITLE
Fix overflow when using large raster sizes

### PR DESCRIPTION
**Pull request by netthier**
This fixes https://github.com/mthh/contour-rs/issues/12.
It contains breaking changes, as some `u32`s in public function signatures have been swapped with `usize`s, requiring an appropriate version bump.

### CODE REVIEW

**Comment by netthier** [comment]
Huh, what's that failure on nightly there? Seems like f32 literals are broken?

**Comment by netthier** [comment]
Do not merge this, it seems like there is another precision issue. I'll post more details in the issue

**Comment by mthh** [comment]
> I think we're hitting https://github.com/rust-lang/rust/issues/123824 [...] Let me know if you want me to add that to this PR or not.

Yeah I think so. The PR fixing the issue you reference seems to be in the merge queue so no need to worry about that, I think.

> it seems like there is another precision issue. I'll post more details in the issue

Alright :-/

**Comment by mthh** [comment]
Great, thanks for your contribution. I will merge this now (and make a new release later today) because it brings improvements and corrections that are already useful.
And we'll continue the discussion on #14.

**Pull request merged**
